services:
  qdrant:
    image: qdrant/qdrant:v1.13.2
    container_name: smartfarm-qdrant-v2
    ports: ["6333:6333"]
    volumes:
      - ../../smartfarm-search/data/qdrant:/qdrant/storage
    mem_limit: 1g
    networks: [private_net]

  falkordb:
    image: falkordb/falkordb:latest
    container_name: smartfarm-falkordb-v2
    ports: ["6379:6379"]
    environment:
      FALKORDB_ARGS: "--maxmemory 512mb"
    volumes:
      - ../../smartfarm-search/data/falkordb:/data
    mem_limit: 768m
    networks: [private_net]

  llama:
    image: ghcr.io/ggml-org/llama.cpp:server
    container_name: smartfarm-llama-v2
    command:
      - --model
      - ${LLAMA_MODEL_PATH:-/models/Qwen3-4B-Q4_K_M.gguf}
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --ctx-size
      - ${LLAMA_CTX_SIZE:-8192}
    ports: ["45857:8080"]
    volumes:
      - ../../smartfarm-search/models:/models
    mem_limit: 3g
    networks: [private_net]

  api:
    build:
      context: ../../smartfarm-search
      dockerfile: Dockerfile
    container_name: smartfarm-api-v2
    ports: ["41177:41177"]
    depends_on: [qdrant, falkordb, llama]
    environment:
      - HOST=0.0.0.0
      - PORT=41177
      - LLMLITE_HOST=http://llama:8080
      - LLM_BACKEND=${LLM_BACKEND:-llama_cpp}
      - OPENAI_COMPAT_BASE_URL=${OPENAI_COMPAT_BASE_URL:-}
      - OPENAI_COMPAT_API_KEY=${OPENAI_COMPAT_API_KEY:-}
      - OPENAI_COMPAT_MODEL=${OPENAI_COMPAT_MODEL:-}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - FALKORDB_HOST=falkordb
      - FALKORDB_PORT=6379
      - PRIVATE_LLM_POLICY=${PRIVATE_LLM_POLICY:-local_only}
      - SOVEREIGNTY_ENFORCED=${SOVEREIGNTY_ENFORCED:-true}
      - PRIVATE_EGRESS_BLOCK=${PRIVATE_EGRESS_BLOCK:-true}
      - ALLOW_DEV_REMOTE_PRIVATE=${ALLOW_DEV_REMOTE_PRIVATE:-false}
    volumes:
      - ../../smartfarm-search/data:/app/data
    mem_limit: 2g
    networks: [private_net]

networks:
  private_net:
    internal: true
