services:
  qdrant:
    image: qdrant/qdrant:v1.13.2
    container_name: smartfarm-ingest-qdrant
    ports: ["6333:6333"]
    volumes:
      - ../../smartfarm-search/data/qdrant:/qdrant/storage

  falkordb:
    image: falkordb/falkordb:latest
    container_name: smartfarm-ingest-falkordb
    ports: ["6379:6379"]
    volumes:
      - ../../smartfarm-search/data/falkordb:/data

  ingest-worker:
    build:
      context: ../../smartfarm-ingest
      dockerfile: Dockerfile
    container_name: smartfarm-offline-ingest
    depends_on: [qdrant, falkordb]
    environment:
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.featherless.ai/v1}
      - API_KEY=${API_KEY:-}
      - KIMI_API_BASE=${KIMI_API_BASE:-https://api.moonshot.cn/v1}
      - KIMI_API_KEY=${KIMI_API_KEY:-}
      - KIMI_MODEL=${KIMI_MODEL:-moonshot-v1-8k}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - FALKORDB_HOST=falkordb
      - FALKORDB_PORT=6379
    volumes:
      - ../../smartfarm-ingest:/app
      - ../../smartfarm-search/data:/app/output

  evaluator:
    build:
      context: ../../smartfarm-benchmarking
      dockerfile: Dockerfile
    container_name: smartfarm-evaluator-v2
    depends_on: [qdrant, falkordb]
    environment:
      - OPENAI_COMPAT_BASE_URL=${OPENAI_COMPAT_BASE_URL:-https://api.featherless.ai/v1}
      - OPENAI_COMPAT_API_KEY=${OPENAI_COMPAT_API_KEY:-${OPENAI_API_KEY:-}}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.featherless.ai/v1}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - RAGAS_MODEL=${RAGAS_MODEL:-openai/gpt-oss-120b}
    volumes:
      - ../../output:/app/output
