services:
  qdrant:
    image: qdrant/qdrant:v1.13.2
    container_name: smartfarm-ingest-qdrant
    ports: ["6333:6333"]
    volumes:
      - ../../smartfarm-search/data/qdrant:/qdrant/storage

  falkordb:
    image: falkordb/falkordb:latest
    container_name: smartfarm-ingest-falkordb
    ports: ["6379:6379"]
    volumes:
      - ../../smartfarm-search/data/falkordb:/data

  ingest-worker:
    build:
      context: ../../smartfarm-ingest
      dockerfile: Dockerfile
    container_name: smartfarm-offline-ingest
    depends_on: [qdrant, falkordb]
    environment:
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.featherless.ai/v1}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-${API_KEY:-}}
      - OPENAI_MODEL=${OPENAI_MODEL:-Qwen/Qwen2.5-32B-Instruct}
      - OPENAI_MODEL_CANDIDATES=${OPENAI_MODEL_CANDIDATES:-Qwen/Qwen2.5-14B-Instruct,Qwen/Qwen2.5-7B-Instruct,meta-llama/Llama-3.1-8B-Instruct}
      - HF_TOKEN=${HF_TOKEN:-${HUGGINGFACE_HUB_TOKEN:-}}
      - HUGGINGFACE_HUB_TOKEN=${HUGGINGFACE_HUB_TOKEN:-${HF_TOKEN:-}}
      - EMBED_BACKEND=${EMBED_BACKEND:-openai_compatible}
      - EMBED_BASE_URL=${EMBED_BASE_URL:-${OPENAI_BASE_URL:-https://api.featherless.ai/v1}}
      - EMBED_API_KEY=${EMBED_API_KEY:-${OPENAI_API_KEY:-${API_KEY:-}}}
      - EMBED_MODEL=${EMBED_MODEL:-Qwen/Qwen3-VL-Embedding-2B}
      - EMBED_DIM=${EMBED_DIM:-512}
      - EMBED_TIMEOUT=${EMBED_TIMEOUT:-30}
      - EMBED_BATCH_SIZE=${EMBED_BATCH_SIZE:-8}
      - DOCLING_VLM_PROFILE=${DOCLING_VLM_PROFILE:-enabled}
      - DOCLING_ENABLE_VLM=${DOCLING_ENABLE_VLM:-true}
      - DOCLING_VLM_MODEL=${DOCLING_VLM_MODEL:-}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - FALKORDB_HOST=falkordb
      - FALKORDB_PORT=6379
    volumes:
      - ../../smartfarm-ingest:/app
      - ../../smartfarm-search/data:/app/output

  evaluator:
    build:
      context: ../../smartfarm-benchmarking
      dockerfile: Dockerfile
    container_name: smartfarm-evaluator
    depends_on: [qdrant, falkordb]
    environment:
      - OPENAI_COMPAT_BASE_URL=${OPENAI_COMPAT_BASE_URL:-https://api.featherless.ai/v1}
      - OPENAI_COMPAT_API_KEY=${OPENAI_COMPAT_API_KEY:-${OPENAI_API_KEY:-}}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.featherless.ai/v1}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - HF_TOKEN=${HF_TOKEN:-${HUGGINGFACE_HUB_TOKEN:-}}
      - HUGGINGFACE_HUB_TOKEN=${HUGGINGFACE_HUB_TOKEN:-${HF_TOKEN:-}}
      - RAGAS_MODEL=${RAGAS_MODEL:-openai/gpt-oss-120b}
    volumes:
      - ../../output:/app/output
